### ISSUE TITLE
Edge-Cases from plone.restapi examples

### ISSUE THREAD

**Issue by lukasgraf** [collective/sphinxcontrib-httpexample#1]
- [x] Our requests don't always have an `Authorization` header:
    ```python
      File "/Users/lukasgraf/src/plone.restapi-docs/extras/sphinxcontrib-httpexample/src/sphinxcontrib/httpexample/parsers.py", line 38, in auth
        method, token = self.headers.get('Authorization').split()
    ```
- [x] Issue with a POST request not appearing to have `headers`:
    ```python
    Exception occurred:
      File "/Users/lukasgraf/src/plone.restapi-docs/extras/sphinxcontrib-httpexample/src/sphinxcontrib/httpexample/parsers.py", line 30, in __init__
        self.headers = capitalize_keys(dict(self.headers.items()))
    AttributeError: HTTPRequest instance has no attribute 'headers'
    ```
    Offending data:
    ```
    (Pdb) HTTPRequest('POST /plone/front-page/@workflow/publish\r\nAccept: application/json').headers
    *** AttributeError: HTTPRequest instance has no attribute 'headers'
    ```
    ✅ Solved: Request was missing the `HTTP/1.1` from the request line

**Comment by datakurre** [comment]
@lukasgraf  Authorization-header was fixed in https://github.com/datakurre/sphinxcontrib-httpexample/commit/10c526966135d993b8ce63a61c69e94c477b709c#diff-b10bb6055c2d2e2fedbf030a3ca263eeL39 (Sorry for my mistake that I didn't make it a proper separate commit.)

**Comment by lukasgraf** [comment]
@datakurre already tested, works! 👍 💚 🍰
