### ISSUE TITLE
Visual consistency with sphinx_tabs

### ISSUE THREAD

**Issue by AWhetter** [collective/sphinxcontrib-httpexample#25]
[sphinx_tabs](https://github.com/djungelorm/sphinx-tabs) allows you to use tabs in Sphinx documentation.
This is a very specific use case but I am using both sphinx_tabs and httpexample together. At the moment they look different but could we add some visual consistency between the two?
Possibly even going to far as to have httpexample use sphinx-tabs under the hood. Doing this would make overriding the theme of both easier because they would use the same html elements and classes.

**Comment by datakurre** [comment]
We cannot change the directives or output structure used, but I would not mind us depending directly on sphinx_tabs just to be able to use its javascripts and styles for tabbing.

**Comment by AWhetter** [comment]
Can you expand on what you mean by output structure? Do you mean that the html output from the directive would need to be that same as what it is now?

**Comment by datakurre** [comment]
Yes, we definitely cannot change the directive nor require changes in existing documentations.

For output this plugin has nothing special, but only reuses existing Docutils/Sphinx doctree components.

The current tabbing is just a few lines a jquery and styles. It should be easily replaceable with something that mutates dom to fit sphinx_tabs styles.
