### ISSUE TITLE
sphinxcontrib-httpexample.js not available on readthedocs

### ISSUE THREAD

**Issue by palango** [collective/sphinxcontrib-httpexample#28]
In our docs (https://raiden-network.readthedocs.io/en/stable/rest_api.html#get--api-(version)-address) We have the issues that the `sphinxcontrib-httpexample.js` file cannot be loaded and thus the docs look strange.

```
Loading failed for the <script> with source “https://raiden-network.readthedocs.io/en/stable/_static/sphinxcontrib-httpexample.js”.
```

Do you have any issue what could cause that. Locally the `sphinxcontrib-httpexample.js` file is properly put into `_static`.

**Comment by datakurre** [comment]
@palango I recall we had the same issue for the docs of this add-on. It is possible that readthedocs has some restrictions.

You manually copy and include those files in the static folder of your docs similarly to https://github.com/collective/sphinxcontrib-httpexample/tree/master/src/sphinxcontrib/httpexample/static

**Comment by palango** [comment]
Thanks @datakurre . Adding these fixed the issue.
