### ISSUE TITLE
Force order of headers in req/resp files.

### ISSUE THREAD

**Issue by tisto** [collective/sphinxcontrib-httpexample#4]
When working with plone.restapi I see a lot of git conflicts that look like this:

```
 GET /plone/non-existing-resource HTTP/1.1
-Accept: application/json
 Authorization: Basic YWRtaW46c2VjcmV0
+Accept: application/json
```

It seems we are not forcing a particular order on the headers. Maybe we can just sort them alphabetically? cc @datakurre @csenger

**Comment by datakurre** [comment]
AFAIK plone.restapi test_documentation generates the http examples, which are then just consumed by httpexample. So, the sorting should be done there. httpexample already sorts headers in generated example commands.

**Comment by tisto** [comment]
@datakurre yeah. I just saw that in our code. Sorry for reporting the bug in the wrong project. :) https://github.com/plone/plone.restapi/issues/263
