### ISSUE TITLE
Add documentation example for URL parameters support

### ISSUE THREAD

**Issue by datakurre** [collective/sphinxcontrib-httpexample#40]
From examples at https://github.com/collective/sphinxcontrib-httpexample/pull/38

**Comment by ludaavics** [comment]
Just making sure you saw [this](https://github.com/collective/sphinxcontrib-httpexample/pull/38/files#diff-6b8768d928ef9ab4f13707da19516369R196).

**Comment by datakurre** [comment]
Already fixed in https://github.com/collective/sphinxcontrib-httpexample/pull/38/files#diff-6b8768d928ef9ab4f13707da19516369R196
