### ISSUE TITLE
New release broken?

### ISSUE THREAD

**Issue by gforcada** [collective/sphinxcontrib-httpexample#44]
I've been using this great Sphinx extension and every time I was setting it up, I ended up with a broken tabs being displayed (i.e. only the first one `HTML` being displayed but no content).

Switching back to 0.9.1 has been the way to fix it so far. I thought that Sphinx 2.0.0 (rather than 1.7.9) or Pygments 2.3.1 (rather than 2.2.0) were the problem, but at least locally, the only version pin that makes the tab not rendering properly is the version bump from 0.9.1 to 0.10.1 from this extension.

Am I the only one seeing this? :thinking: 

What does not help much is that there is no warning/error on the output saying that something broke. Is there any way to get some debugging from Sphinx extensions?

**Comment by datakurre** [comment]
This is most probably issue with the javascript & CSS injected by this add-on.

**Comment by datakurre** [comment]
I froze my (old) KGS into requirements.txt and https://sphinxcontrib-httpexample.readthedocs.io/en/latest/ is building successfully.

I leave this issue open. It could be renamed when the root issue is known.

**Comment by gforcada** [comment]
I will try to check it within this week, but we changed our approach regarding documentation and embraced django REST framework way :sweat_smile:
