### ISSUE TITLE
Parse responses even if they don't specify the HTTP version

### ISSUE THREAD

**Issue by gforcada** [collective/sphinxcontrib-httpexample#45]
I'm writing the documentation of a django REST framework based service and I noticed that copy&pasting the output given by the browsable API from django REST framework does not work with this sphinx extension.

Seems that the problem is that django returns `HTTP 201 Created` rather than `HTTP/1.1 201 Created`.

**Comment by gforcada** [comment]
After having a look at the code, it seems that the problem is from upstream (i.e. in Python's BaseHTTPRequestHandler :confused: )

**Comment by datakurre** [comment]
Possibly the version could be injected there before calling?

**Comment by gforcada** [comment]
yes, that's what I thought as well, I will see if I have time to look at it.

**Comment by datakurre** [comment]
at least a failing test would be great!

Curious that Django REST API was done with such, almost non-standard, responses.

**Comment by datakurre** [comment]
Should be fixed in 0.10.3
