### ISSUE TITLE
How to include from a file?

### ISSUE THREAD

**Issue by kotaweav** [collective/sphinxcontrib-httpexample#87]
Hi! First of all thanks for the super cool project!
I was wondering if there is support for loading a file similar to `.. literalinclude::` directive.

Thanks!

**Comment by datakurre** [comment]
Request and response could be read from files as in:

https://sphinxcontrib-httpexample.readthedocs.io/en/latest/usage.html#examples-with-external-sources

The first use case for this was to generate examples from request and response files also used when testing the documented API in question.
