### ISSUE TITLE
Enhancement: Add 'JavaScript' Tab to Display JavaScript Client Method in sphinxcontrib-httpexample

### ISSUE THREAD

**Issue by Hrittik20** [collective/sphinxcontrib-httpexample#90]
We propose adding a custom "JavaScript" tab to sphinxcontrib-httpexample. The purpose of this tab is to display the JavaScript client method, specifically `createAliasesMutation`, which developers can use to call the Plone REST API endpoint for adding URL aliases in bulk.

Refer to the discussion in [this pull request](https://github.com/plone/volto/pull/5576) for additional details and context.

**Comment by datakurre** [comment]
Should we call this tab simply “Plone”, because it would be very Plone specific?

Could you provide some code examples for these calls (what kind of code should be displayed on the tab)?

**Comment by Hrittik20** [comment]
We want the tab title to be "JavaScript". Perhaps we can explore creating a custom tab that allows us to set the title according to our preferences. 
We plan to display simple code snippets corresponding to Plone REST API calls. Specifically, we aim to output the JavaScript client method `createAliasesMutation`.

**Comment by datakurre** [comment]
Ok. In configuration it could be plone_javascript (or something other unique), but the display value could be JavaScript. That’s way easier than introducing custom labels until there are enough similar use cases to make it worth of the effort. 

For further design, I’m really really waiting to see more example results before thinking this more out of thin air :)

**Comment by Hrittik20** [comment]
@datakurre We are trying to achieve this structure. However, I can't seem to figure out how to format the request body like `http` or `httpie`. Do you know how to do it?

![Capture](https://github.com/collective/sphinxcontrib-httpexample/assets/49366463/32941188-c80d-4180-951d-a5c86dbf4534)

**Comment by datakurre** [comment]
I don't think that there is any magic in it. The builder returns formatted string, and the directive places it within Sphinx CodeBlock.

**Comment by datakurre** [comment]
Released in https://pypi.org/project/sphinxcontrib-httpexample/1.2/
